version: '3.8'
services:
    db:
        image: mysql:5.6
        container_name: bdd_mariage_test
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            #MYSQL_USER: 'admin' #pas de droit
            #MYSQL_PASSWORD: 'admin' #pas de droit
            MYSQL_ROOT_PASSWORD: 'admin'
        networks:
          - dev

    phpmyadmin:
        # admin
        image: phpmyadmin
        container_name: php_myadmin_mariage_test
        #restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
          - dev

    www:
        build:
            context: ./php
        container_name: www_docker_php8_mariage_test
        ports:
            - "8081:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        sysctls:
            - net.ipv4.ip_unprivileged_port_start=0
        #restart: always
        networks:
            - dev
    
networks:
    dev:

volumes:
    db-data:
